import { Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Paper, Box } from '@mui/material'


const Page2 = () => {
    return (
        <Box className={'Page2-box'} sx={{ px: 35, backgroundColor: 'rgb(250, 232, 201)' }}>
            <Box className={'header2'}>
            <button className={'header2-button'} type="button" onClick={() => window.location.href = '/'}>ホームへ</button>
            </Box>

            <div className={'Page2'}>
                <TableContainer component={Paper} className={'Page2-table'}>
                    <Table>
                        <TableHead>
                            <TableRow>
                                <TableCell>質問例</TableCell>
                            </TableRow>
                        </TableHead>

                        <TableBody>
                            <TableRow>
                                <TableCell>ツイステッドワンダーランドの学園名は？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>ディズニー作品の中でツイステはどの作品をモチーフにしている？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>監督生はどの寮に所属している？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>ハーツラビュル寮のモチーフは？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>サバナクロー寮のモチーフは？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>オクタヴィネル寮のモチーフは？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>スカラビア寮のモチーフは？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>ポムフィオーレ寮のモチーフは？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>イグニハイド寮のモチーフは？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>ディアソムニア寮のモチーフは？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>ツイステはどんなゲーム？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>ツイステッドワンダーランドって何？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>どんなキャラクターが登場するの？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>このゲームの目的は何ですか？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>ストーリーの設定はどんな感じ？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>魔法は使えるの？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>主人公はどんなキャラクターですか？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>グリムって誰？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>どのプラットフォームで遊べる？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>課金要素はありますか？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>ナイトレイブンカレッジにはいくつの寮があるの？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>学園の寮はどうやって決まるの？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>戦闘システムはどんな感じですか？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>リズミックって何？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>キャラクター同士の関係はどうなっていますか？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>寮はどのディズニーキャラクターをモチーフにしているの？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>プレイヤーの選択肢はストーリーに影響するの？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>ストーリーは一話完結型？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>ゲームの更新頻度はどのくらい？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>ゲーム内でキャラクターを強化する方法は？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>どのキャラクターを育てるべき？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>どんなイベントがあるの？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>どのイベントがオススメ？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>ゲーム内の通貨は何？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>「ツイステッドワンダーランド」はどんなジャンルのゲームですか？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>ディズニーキャラクターは出てきますか？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>プレイヤーはどのキャラクターを操作しますか？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>「ナイトレイブンカレッジ」とは何ですか？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>どのようなプレイスタイルですか？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>無料で遊べますか？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>ゲーム内の課金要素は何ですか？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>ディズニー以外の要素もありますか？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>マルチプレイはできますか？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>ストーリーはどのくらいの長さですか？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>キャラクターはどうやって強化しますか？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>初心者におすすめのキャラクターは？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>イベントはどのくらいの頻度で行われますか？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>このゲームは何年から始まりましたか？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>寮の違いは何ですか？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>バトルはどのように進行しますか？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>このゲームの魅力は何ですか？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>ストーリーをスキップすることはできますか？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>ゲームはどのように進行しますか？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>アイテムの入手方法は？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>ハーツラビュル寮長の名前は？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>サバナクロー寮長の名前は？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>オクタヴィネル寮長の名前は？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>スカラビア寮長の名前は？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>ポムフィオーレ寮長の名前は？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>イグニハイド寮長の名前は？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>ディアソムニア寮長の名前は？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>ツイステはどんなストーリーなの？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>ナイトレイブンカレッジ（NRC）とは？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>７つの寮の名前は？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>寮とは？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>ハーツラビュル副寮長の名前は？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>オクタヴィネル副寮長の名前は？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>スカラビア副寮長の名前は？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>ポムフィオーレ副寮長の名前は？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>ディアソムニア副寮長の名前は？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>「ユニーク魔法」とは何？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>主人公（監督生）が最初に会うキャラクターは？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>主人公（監督生）の学年は？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>主人公（監督生）の名前は？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>寮長会議とは何？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>グリムの夢は？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>ハーツラビュル寮の寮生は？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>リドルのユニーク魔法の名前は？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>トレイの性格はどんな感じですか？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>ケイトが好きなことは？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>エースの趣味は何ですか？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>デュースの好きな食べ物は？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>レオナの身長は？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>ラギーの声優は？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>ジャックの利き手は？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>アズールの元ネタは？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>ジェイドの出身は？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>フロイドの嫌いなことは？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>カリムはなぜジャミルを信頼しているのですか？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>ジャミルの所属する部活は？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>ヴィルの所属する部活は？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>ルークの出身は？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>エペルの趣味は何ですか？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>イデアの最大の恐れは？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>オルトの夢は何ですか？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>マレウスの出身は？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>リリアの所属する部活は？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>シルバーは誰に育てられましたか？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>セベクの家族構成は？</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>本編の１章の内容は？</TableCell>
                            </TableRow>
                        </TableBody>
                    </Table>
                </TableContainer>
            </div>
        </Box>
    );
};

export default Page2;